[package]
name = "rusty-controller"
version = "0.1.1"
authors = ["Frank Lyaruu <flyaruu@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { workspace=true }
esp-backtrace  = { workspace=true }
esp-println = { workspace=true }
log = { workspace=true }
esp-alloc = { workspace=true }
esp-wifi  = { workspace=true }
heapless = { workspace=true }
esp-hal-embassy = { workspace=true }
embassy-time = { workspace=true }
embassy-executor =  { workspace=true }
embassy-sync =  { workspace=true }
embassy-futures =  { workspace=true }
embedded-svc =  { workspace=true }
embedded-io =  { workspace=true }
embedded-hal =  { workspace=true }
embedded-hal-async =  { workspace=true }
embedded-io-async =  { workspace=true }

protocol = { path = "../protocol" }
#rotary-encoder-hal = { path="../../rotary-encoder-hal/", features = ["embedded-hal-1"]}
rotary-encoder-hal = { git="https://github.com/flyaruu/rotary-encoder-hal", features = ["embedded-hal-1"], rev="b8c5baecb99b686a7729ecc817dad6043030c80f" }
